In [1]:
import torch

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([1., 2., 3., 4.])
t2

tensor([1., 2., 3., 4.])

In [6]:
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])

In [7]:
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [8]:
t1.shape

torch.Size([])

In [9]:
t2.shape

torch.Size([4])

In [10]:
t3.shape

torch.Size([3, 2])

In [11]:
t4.shape

torch.Size([2, 2, 3])

In [12]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [14]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [15]:
y.backward()

In [16]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [17]:
import numpy as np
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [19]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [20]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [21]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])